FROM docker.elastic.co/kibana/kibana:6.7.2

#RUN bin/kibana-plugin remove x-pack && \
#    kibana 2>&1 | grep -m 1 "Optimization of .* complete"

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
