FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.2

RUN bin/elasticsearch-plugin remove x-pack --purge

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
